name: API Automation Demo

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule : 
    - cron: 00 03 * * *
    #- cron: 00 03 1 * *

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Execute Tests
      run: mvn clean test -Dsuite=suite -X

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.5.0
      with:
        name: Logs
        path: logs/
